"""Report generation: daily readiness (Sonnet) and weekly review (Opus).

Each report is generated by running the coordinator with a fixed prompt, persisted to
the DB so the web UI can show history, and pushed to any configured notify channels.
"""
from __future__ import annotations

from datetime import date

from claude_agent_sdk import AssistantMessage, ClaudeSDKClient, TextBlock

from coach import notify
from coach.agents.coordinator import build_options
from coach.config import settings
from coach.db import SessionLocal
from coach.models import Report

READINESS_PROMPT = """Give me today's readiness check. Keep it short — a quick morning brief.
Look at the last 3-5 days only:
- recent training load and which muscle groups were hit (strength), and any hard/long
  cardio that adds recovery cost
- the latest body-composition reading if it's relevant

Then recommend: train or rest today, and if training, what to prioritize and what to go
easy on. Note any recovery red flags. A few tight bullets, no long analysis.
"""

REVIEW_PROMPT = """Produce my weekly training review. Consult all relevant subagents:
- strength (Hevy): volume, key lifts and 1RM trends, stalls, and progression for next week
- cardio (Strava): aerobic load this week and whether it's interfering with lifting recovery
- body (Withings): weight and body-composition trend, interpreted against my strength goal

Cover the last 7 days versus the prior weeks. Be specific with dates and numbers. End with
a short, prioritized action plan for the coming week. Use clear sections with headers.
"""

# kind -> (prompt, model, email/notion subject prefix)
_SPECS = {
    "readiness": (READINESS_PROMPT, None, "Daily readiness"),
    "weekly": (REVIEW_PROMPT, settings.coach_review_model, "Weekly training review"),
}


async def generate(kind: str) -> str:
    """Run the coordinator and return the report text. Does not persist or notify."""
    prompt, model, _ = _SPECS[kind]
    options = build_options(model=model)  # model=None -> default Sonnet
    parts: list[str] = []
    async with ClaudeSDKClient(options=options) as client:
        await client.query(prompt)
        async for message in client.receive_response():
            if isinstance(message, AssistantMessage):
                for block in message.content:
                    if isinstance(block, TextBlock):
                        parts.append(block.text)
    return "".join(parts).strip()


def save_report(kind: str, content: str) -> Report:
    with SessionLocal() as s:
        report = Report(kind=kind, content=content)
        s.add(report)
        s.commit()
        s.refresh(report)
        s.expunge(report)
        return report


async def generate_and_store(kind: str) -> Report:
    """Generate a report, persist it, and push to notify channels. Returns the row."""
    content = await generate(kind)
    report = save_report(kind, content)
    subject = f"{_SPECS[kind][2]} — {date.today():%Y-%m-%d}"
    notify.send(subject, content)
    return report
