"""Report generation: daily readiness and weekly review.

Each report is generated by running the coordinator with a fixed prompt, persisted to
the DB so the web UI can show history, and pushed to any configured notify channels.

The coordinator's system prompt already carries the athlete's current focus (see
coach.focus / coach.agents.coordinator), so these prompts stay goal-agnostic and let the
focus drive interpretation. The weekly review also yields a structured action plan that is
stored as checkable, goal-linked action items for the current week.
"""
from __future__ import annotations

import asyncio
import json
import logging
import re
from datetime import date, datetime, timedelta
from zoneinfo import ZoneInfo

from sqlalchemy import select

from coach import llm, notify, plan, readiness_score, workout_delivery
from coach.agents.gemini import run_once
from coach.config import settings
from coach.db import SessionLocal
from coach.models import ActionItem, PlanDay, Report
from coach.web import stats

log = logging.getLogger("coach.reports")


class ReportGenerationError(RuntimeError):
    """Raised when the model is unavailable or returns nothing usable.

    Lets the web layer map a transient upstream failure (e.g. the model is
    busy / 503) to a clean error instead of leaking a raw 500.
    """

READINESS_PROMPT = """Give me today's readiness check. This is a training brief — the point is to
tell me WHAT TO TRAIN TODAY. Keep it short and decisive.

Start with EXACTLY one line in this format, nothing before it:
Verdict: <Train | Train easy | Rest> — <what to train today and why> (e.g. which split /
muscle groups are freshest, or that it's a cardio/rest day)

Then lead with TRAINING — this is the core of the brief:
- Walk the last 3-5 days session by session (date + what was hit). For each, judge how
  recovered that muscle group / system is now (e.g. legs <24h out = skip; a push session
  5 days ago = fully clear). Call out any hard/long cardio and its residual recovery cost.
- From that, make the call: which split or muscle groups have the most clearance today,
  and what to specifically avoid (don't stack onto something <24-48h old). If adding
  cardio, say how much and how easy.

Then a short supporting check (only let this MODIFY the training call, don't make it the
focus): this morning's Garmin recovery — HRV vs baseline, sleep, resting HR vs 7-day avg,
Body Battery, and the acute:chronic load ratio (ACWR, sweet spot 0.8–1.3). If recovery is
fine, say so in one line and move on. If something's off (suppressed HRV, poor sleep,
rising resting HR, ACWR spike >1.3), use it to dial the verdict down.

Then the latest body-composition reading if it's relevant to today's call.

End with any red flags. No long analysis — be concrete and training-first.
"""

HEALTH_PROMPT = """Give me a recovery & health read from my Garmin data. This drives
my training decision for today, so be concrete.

Start with EXACTLY one line, nothing before it:
Verdict: <Recovered | Moderate | Compromised> — <a few words on the main driver>

Then tight sections (use the recovery tools — pull a trend, not just today):
- Recovery now: HRV (value vs. baseline + status), Body Battery, sleep last night
  (duration, score, deep/REM), resting HR (vs its 7-day average), overnight respiration
  and SpO2 if notable. Include Garmin training-readiness score & level only if present
  (some watches don't report it — don't dwell on it if absent).
- Trend (last 7-14 days): is HRV/sleep/resting-HR improving, stable, or degrading?
  Call out accumulating fatigue or a recovery rebound.
- Training load: training status and the acute:chronic workload ratio (ACWR — show acute
  vs chronic load and the ratio; sweet spot is 0.8–1.3, flag if I'm spiking >1.3 or
  detraining <0.8). Am I building, maintaining, or overreaching? VO2max and fitness-age
  trend if either moved.
- What to do today: how hard to go and what to prioritise, judged against my focus.
  Flag clear red flags (suppressed HRV, poor sleep streak, rising resting HR, ACWR spike).

Be specific with numbers and dates. Keep it scannable.
"""

REVIEW_PROMPT = """Produce my weekly training review. Use all relevant data tools and cover:
- strength (Hevy): volume, key lifts and 1RM trends, stalls, and progression for next week
- cardio (Strava): aerobic load this week and whether it's interfering with recovery
- recovery & load (Garmin): pull the recovery trend for the week — HRV (vs baseline),
  sleep, resting HR, Body Battery, and the training load picture: training status and the
  acute:chronic workload ratio (ACWR — sweet spot 0.8–1.3). Is load building safely or
  spiking into overreaching? Note any VO2max / fitness-age movement.
- body (Withings): weight and body-composition trend, interpreted against my current focus

Cover the last 7 days versus the prior weeks. Be specific with dates and numbers. End with
a section titled "Action plan" — a short, prioritized list of concrete things to do this
coming week, each on its own bullet. Use clear sections with headers.
"""

# Metrics an action can be linked to so the UI tracks live progress. Keep in sync with
# the weekly goals in coach.web.app (DEFAULT_GOALS).
_ACTION_METRICS = {
    "weekly_strength_sessions": "strength sessions this week (count)",
    "weekly_active_days": "active days this week (count)",
    "weekly_cardio_distance": "cardio distance this week (km)",
    "weekly_strength_volume": "strength volume / tonnage this week (kg)",
}

_EXTRACT_PROMPT = """From the weekly training review below, extract the coming week's action
plan as a JSON array. Each element: {{"title": str, "metric": str|null, "target": number|null}}.

- "title": a short imperative action (max ~10 words), no markdown.
- If an action maps to one of these trackable metrics, set "metric" to its key and "target"
  to the weekly numeric target implied by the action; otherwise both null:
{metrics}

Return 3-6 items, most important first. Output ONLY the JSON array, nothing else.

REVIEW:
{review}
"""

# kind -> (prompt, model, email/notion subject prefix)
_SPECS = {
    "readiness": (READINESS_PROMPT, None, "Daily readiness"),
    "weekly": (REVIEW_PROMPT, settings.coach_review_model, "Weekly training review"),
    "health": (HEALTH_PROMPT, None, "Health & recovery"),
}


async def generate(kind: str, *, prompt_context: str | None = None) -> str:
    """Run the coordinator and return the report text. Does not persist or notify."""
    prompt, model, _ = _SPECS[kind]
    if prompt_context:
        prompt = f"{prompt}\n\nAUTHORITATIVE COACH CALCULATION:\n{prompt_context}"
    try:
        return await run_once(prompt, model=model)
    except Exception as exc:  # noqa: BLE001 - surface a clean, retryable error
        raise ReportGenerationError(
            "Coach couldn't generate the report — the model may be busy. "
            "Try again in a moment."
        ) from exc


def save_report(
    kind: str,
    content: str,
    *,
    review_date: date | None = None,
    readiness: readiness_score.ReadinessResult | None = None,
    plan_week_start: date | None = None,
    workflow_status: str = "complete",
    workflow_error: str | None = None,
) -> Report:
    with SessionLocal() as s:
        report = Report(
            kind=kind,
            content=content,
            review_date=review_date,
            readiness_score=readiness.score if readiness else None,
            readiness_details_json=(
                json.dumps(readiness.components, sort_keys=True) if readiness else None
            ),
            plan_week_start=plan_week_start,
            workflow_status=workflow_status,
            workflow_error=workflow_error,
        )
        s.add(report)
        s.commit()
        s.refresh(report)
        s.expunge(report)
        return report


def _week_start(d: date | None = None) -> date:
    d = d or date.today()
    return d - timedelta(days=d.weekday())  # Monday


def _local_today() -> date:
    return datetime.now(ZoneInfo(settings.scheduler_timezone)).date()


def _latest_health_day(on_or_before: date) -> dict | None:
    days = stats.health(end=on_or_before.isoformat()).get("days", [])
    return days[-1] if days else None


async def extract_actions(review: str) -> list[dict]:
    """Ask a lightweight, tool-less model to turn the review's action plan into
    structured items."""
    metrics = "\n".join(f"  - {k}: {desc}" for k, desc in _ACTION_METRICS.items())
    raw = await llm.complete(
        _EXTRACT_PROMPT.format(metrics=metrics, review=review), max_tokens=1024
    )
    match = re.search(r"\[.*\]", raw, re.DOTALL)
    if not match:
        return []
    try:
        data = json.loads(match.group(0))
    except json.JSONDecodeError:
        log.warning("could not parse extracted actions: %s", raw[:200])
        return []
    out: list[dict] = []
    for item in data if isinstance(data, list) else []:
        title = str(item.get("title", "")).strip()
        if not title:
            continue
        metric = item.get("metric")
        if metric not in _ACTION_METRICS:
            metric = None
        target = item.get("target")
        try:
            target = float(target) if target is not None else None
        except (TypeError, ValueError):
            target = None
        out.append({"title": title[:200], "metric": metric, "target": target})
    return out[:6]


def store_week_actions(
    report_id: int,
    actions: list[dict],
    *,
    week_start: date | None = None,
) -> int:
    """Replace this week's auto-generated actions with a fresh set from a review."""
    if not actions:
        return 0
    ws = week_start or _week_start()
    due = ws + timedelta(days=6)
    with SessionLocal() as s:
        existing = (
            s.query(ActionItem)
            .filter(ActionItem.auto.is_(True), ActionItem.week_start == ws)
            .all()
        )
        for row in existing:
            s.delete(row)
        for a in actions:
            s.add(
                ActionItem(
                    title=a["title"],
                    metric=a.get("metric"),
                    target_value=a.get("target"),
                    week_start=ws,
                    due_date=due,
                    auto=True,
                    source_report_id=report_id,
                )
            )
        s.commit()
    return len(actions)


def _set_workflow_status(report_id: int, rows) -> None:
    failures = [row for row in rows if row.delivery_status == "failed"]
    with SessionLocal() as session:
        report = session.get(Report, report_id)
        if report is None:
            return
        if failures:
            report.workflow_status = "delivery_failed"
            report.workflow_error = "; ".join(
                f"{row.date}: {row.delivery_error or 'delivery failed'}" for row in failures
            )[:2000]
        else:
            report.workflow_status = "complete"
            report.workflow_error = None
        session.commit()


def reconcile_workflow_statuses() -> int:
    """Refresh report workflow states after background workout-delivery retries."""
    changed = 0
    with SessionLocal() as session:
        candidates = list(
            session.execute(
                select(Report).where(
                    Report.plan_week_start.is_not(None),
                    Report.workflow_status.in_(["publishing", "delivery_failed"]),
                )
            ).scalars()
        )
        for report in candidates:
            week_end = report.plan_week_start + timedelta(days=6)
            delivery_start = (
                report.review_date
                if report.kind == "readiness" and report.review_date is not None
                else report.plan_week_start
            )
            days = list(
                session.execute(
                    select(PlanDay).where(
                        PlanDay.date >= delivery_start,
                        PlanDay.date <= week_end,
                    )
                ).scalars()
            )
            failures = [day for day in days if day.delivery_status == "failed"]
            pending = [day for day in days if day.delivery_status == "pending"]
            status = "delivery_failed" if failures else "publishing" if pending else "complete"
            error = (
                "; ".join(
                    f"{day.date}: {day.delivery_error or 'delivery failed'}"
                    for day in failures
                )[:2000]
                if failures
                else None
            )
            if report.workflow_status != status or report.workflow_error != error:
                report.workflow_status = status
                report.workflow_error = error
                changed += 1
        session.commit()
    return changed


async def generate_and_store(kind: str, *, for_date: date | None = None) -> Report:
    """Generate a report, persist it, and push to notify channels. Returns the row.

    For weekly reviews, also extract the action plan into trackable action items.
    """
    review_day = for_date or _local_today()
    readiness: readiness_score.ReadinessResult | None = None
    plan_week_start: date | None = None
    planned_days = []

    if kind == "readiness":
        health_day = await asyncio.to_thread(_latest_health_day, review_day)
        readiness = readiness_score.calculate(health_day)
        context = (
            f"Coach readiness score: {readiness.score}/100. Components: "
            f"{json.dumps(readiness.components, sort_keys=True)}. Treat this score as fixed: "
            "explain it and make a consistent Train, Train easy, or Rest decision, but do not replace it."
        )
        content = await generate(kind, prompt_context=context)
        plan_week_start = _week_start(review_day)
        try:
            planned_days = await plan.replan_from(
                review_day,
                review_context={
                    "daily_review": content,
                    "readiness_score": readiness.score,
                    "readiness_components": readiness.components,
                },
            )
            planned_days = [day for day in planned_days if day.date >= review_day]
        except plan.PlanGenerationError as exc:
            raise ReportGenerationError(
                "Coach generated the readiness assessment but could not update today's plan. Try again."
            ) from exc
        report = save_report(
            kind,
            content,
            review_date=review_day,
            readiness=readiness,
            plan_week_start=plan_week_start,
            workflow_status="publishing",
        )
    elif kind == "weekly":
        content = await generate(kind)
        actions: list[dict] = []
        try:
            actions = await extract_actions(content)
        except Exception:  # noqa: BLE001 — never fail a report over its action plan
            log.exception("failed to extract weekly actions")
        plan_week_start = _week_start(review_day + timedelta(days=7))
        try:
            planned_days = await plan.generate_week(
                plan_week_start,
                review_context={"weekly_review": content, "actions": actions},
            )
        except plan.PlanGenerationError as exc:
            raise ReportGenerationError(
                "Coach generated the weekly assessment but could not create next week's plan. Try again."
            ) from exc
        report = save_report(
            kind,
            content,
            review_date=review_day,
            plan_week_start=plan_week_start,
            workflow_status="publishing",
        )
        try:
            store_week_actions(report.id, actions, week_start=plan_week_start)
        except Exception:  # noqa: BLE001 — never fail a review over action persistence
            log.exception("failed to store weekly actions")
    else:
        content = await generate(kind)
        report = save_report(kind, content, review_date=review_day)

    if planned_days:
        delivered = await asyncio.to_thread(workout_delivery.publish_days, planned_days)
        await asyncio.to_thread(_set_workflow_status, report.id, delivered)
        with SessionLocal() as session:
            refreshed = session.get(Report, report.id)
            if refreshed is not None:
                session.expunge(refreshed)
                report = refreshed
    subject = f"{_SPECS[kind][2]} — {review_day:%Y-%m-%d}"
    notify.send(
        subject,
        content,
        preference_key="weeklyReview" if kind == "weekly" else None,
    )
    return report
